In [13]:
import numpy as np

## Write a Python program to print the NumPy version in your system.

In [66]:
print(np.__version__)

1.20.3


## Write a Python program to reverse an array (first element becomes last).

In [15]:
arr1 = np.random.randn(3,3)
print(arr1)
# Reversed array
print(arr1[::-1])

[[-0.97586813  1.60284293  0.15281299]
 [-0.11426702  0.19019914 -0.58183676]
 [-0.00279308  0.06657566 -0.46061153]]
[[-0.00279308  0.06657566 -0.46061153]
 [-0.11426702  0.19019914 -0.58183676]
 [-0.97586813  1.60284293  0.15281299]]


## Write a Python program to convert a list and tuple into arrays.

In [16]:
inputList = [20,32,34,50,102]
inputTuple = (20,32,34,50,102)
arr2 = np.array(inputList,dtype = np.int32)
print(arr2)
arr3 = np.array(inputTuple, dtype = np.int32)
print(arr3)

[ 20  32  34  50 102]
[ 20  32  34  50 102]


## Write a Python program to find common values between two arrays.

In [17]:
arr1 = np.array([20,30,40,50,100])
arr2 = np.array([10,40,100])
print(np.intersect1d(arr2,arr1))

[ 40 100]


## Write a Python program compare two arrays using numpy.

In [18]:
arr1 = np.array([[130,23,40],[39,32,13]])
arr2 = np.array([[22,23,40],[3,6,13]])
print(arr1 == arr2)

[[False  True  True]
 [False False  True]]


## Write a Python program to change the dimension of an array.

In [19]:
arr1 = np.array([(10,20),(30,40),(50,60)])
# array 1 which has 2 X 3 dimension
print(arr1)
# array 2 which contains 3 X 2 dimension reshaped form of array 1
arr2 = arr1.reshape(2,3)
print(arr2)
# array 3 which contains 1 X 6 dimension reshaped form of array 1
arr3 = arr1.reshape(1,6)
print(arr3)

[[10 20]
 [30 40]
 [50 60]]
[[10 20 30]
 [40 50 60]]
[[10 20 30 40 50 60]]


## Write a Python program (using numpy) to sumof all the multiples of 3 or 5 below 100.

In [20]:
arr1 = np.arange(1,100)
result_array = arr1[(arr1 % 3 == 0) | (arr1 % 5 == 0)]
print(result_array)
print(result_array.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Write a Python program to convert a NumPy array into Python list structure.

In [21]:
arr1 = np.arange(1,10)
result_list = arr1.tolist()
print(result_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## Write a Python program to how to add an extra column to a numpy array.

In [22]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,13).reshape(3,1)
result_array = np.append(arr1,arr2,axis = 1)
print(result_array)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


## Write a Python program to check whether the numpy array is empty or not.

In [23]:
arr1 = np.array([])
if arr1.size == 0:
    print('Array is empty')
else:
    print('Array is not empty')


Array is empty


## Write a Python program to normalize a 3x3random matrix.

In [24]:
arr1 = np.random.randn(3,3)
print("The input matrix is....", arr1)
x_min = arr1.min()
x_max = arr2.max()
# Formula 
## X new = (X — X min)/ (X max — X min)
x_new = (arr1 - x_min) / (x_max - x_min)
print("The Normalized matrix is.....")
print(x_new)

The input matrix is.... [[ 0.65620991 -0.82481065  0.31297004]
 [-0.125351    1.95580182 -1.22360787]
 [ 2.09053753  1.78563014  0.07668137]]
The Normalized matrix is.....
[[0.14215619 0.03015797 0.1161996 ]
 [0.08305274 0.24043436 0.        ]
 [0.25062339 0.22756558 0.0983309 ]]


## How to ignore all numpy warnings (not recommended)?

In [25]:
"We Need to set up Warning controller to ignore all numpy warnings by using the below code..."
#np.seterr(all="ignore")

'We Need to set up Warning controller to ignore all numpy warnings by using the below code...'

## How to swap two rows of an array?

In [26]:
arr1 = np.array([[10,29,30],[20,30,59],[18,23,53]])
result_arr = arr1[::-1]
print(result_arr)

[[18 23 53]
 [20 30 59]
 [10 29 30]]


## Python program to create a random vector of size 10 and sort it.

In [39]:
arr2 = np.random.random(10)
print("Random vector is....")
print(arr2)
arr2.sort()
print('Sorted array is....')
print(arr2)

Random vector is....
[0.94591679 0.72047851 0.62017091 0.81733029 0.61171003 0.73399117
 0.34774478 0.24691938 0.15429297 0.06901006]
Sorted array is....
[0.06901006 0.15429297 0.24691938 0.34774478 0.61171003 0.62017091
 0.72047851 0.73399117 0.81733029 0.94591679]


## Write a Python program to check two random arrays are equal or not.

In [49]:
arr1 = np.random.randint(2,6,10)
arr2 = np.random.randint(2,6,10)

val = np.allclose(arr1,arr2)
if val:
    print('Arrays are equal...')
else:
    print('Arrays are Not equal')

Arrays are Not equal


## Write a Python program to add, subtract, multiply, divide arguments element-wise.

In [54]:
add_result = np.add(1.2,3.9)
print(add_result)
subtract_result = np.subtract(1.2,3.9)
print(subtract_result)
multiply_result = np.multiply(1.2,3.9)
print(multiply_result)
divide_result = np.divide(1.2,3.9)
print(divide_result)

5.1
-2.7
4.68
0.3076923076923077


## Write a Python program to get the dates of yesterday, today and tomorrow.

In [63]:
today_date = np.datetime64('today')
print(f"Today's date is {today_date}")
yesterday_date = today_date - np.timedelta64(1,'D')
print(f"Yesterday's date is {yesterday_date}")
tommorow_date = today_date + np.timedelta64(1,'D')
print(f"Tommorow date is {tommorow_date}")

Today's date is 2022-05-08
Yesterday's date is 2022-05-07
Tommorow date is 2022-05-09
